name: oghu

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: test
      run: go test ./... -v
